# Don't print a new line at the start of the prompt
add_newline = true
# A minimal left prompt
format = """$directory$fill$all$battery${custom.task-count}  
$character"""

# ${custom.task}
# move the rest of the prompt to the right
# right_format = """$all"""
# Use custom format
# format = """
# [┌───────────────────>](bold green)
# [│](bold green)$directory$rust$package
# [└─>](bold green) """

[fill]
symbol = " "
# style = "bold green"

[custom.task-count]
description = "tasks"
command = 'echo  "   $(cat ~/.task/pending.data | wc -l) " '
format = "[$symbol$output]($style) "
style = "bold bg:grey fg:purple"
when = "true"

# [custom.task]
# description = "remaining tasks"
# command = "task-starship"
# format = "[$symbol$output]($style) "
# style = "bold fg:bright-blue"
# when = "true"

# Make prompt a single line instead of two lines
[line_break]
disabled = true

[directory]
truncation_length = 8
truncation_symbol = ".../"
read_only = " 🔒"
home_symbol = "    ~"
style = "bold purple"

# [git_status]
# conflicted = "🏳"
# ahead = "🏎💨"
# behind = "😰"
# diverged = "😵"
# up_to_date = "✓"
# untracked = "🤷‍"
# stashed = "📦"
# modified = "📝"
# staged = '[++\($count\)](green)'
# renamed = "👅"
# deleted = "🗑"

[git_status]
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

# Replace the "❯" symbol in the prompt with "➜"
# [character]                         # The name of the module we are configuring is "character"
# success_symbol = "[➜](bold green)"  # The "success_symbol" is set to "➜" with color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

## Modules
[battery]
full_symbol = "🔋"
charging_symbol = "⚡️"
discharging_symbol = "💀"

##The display configuration option is used to define when the battery indicator should be shown (threshold) and what it looks like (style).

[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]]  # "bold yellow" style when capacity is between 10% and 30%
threshold = 30
style = "bold yellow"

